services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persist Redis data
    restart: unless-stopped

  standalone-worker-small:
    image: standalone-worker
    build:
      context: ../../
      dockerfile: _deployment/docker_compose_workers/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
    depends_on:
      - redis

  standalone-worker-large:
    image: standalone-worker
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
    depends_on:
      - redis

volumes:
  redis_data: